M48
; DRILL file {KiCad 8.0.5+1} date 2024-11-01T08:39:33+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-01T08:39:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X1.9031Y-2.5577
X1.9031Y-2.7486
T2
X1.7839Y-2.5459
X1.7839Y-2.7604
M30
